version: '3.9'

services:
  backend:
    build: .
    working_dir: /src
    env_file:
      - ./src/.env
    volumes:
      - ./src:/src
      - sock-data:/src/tmp
      - public-data:/src/public
    depends_on:
      - db
    networks:
      - blog-app-network
      - default
    tty: true
    stdin_open: true
    # apt-get updateはubuntuのパッケージリストの更新を行なっている（パッケージがリストに載っていないことがある）
    # puma.sockを配置するディレクトリを作成している
    # command: sh -c "apt-get update -qq &&
    #                 apt-get install -y build-essential libpq-dev nodejs &&
    #                 rm -rf /var/lib/apt/lists/* &&
    #                 mkdir -p tmp/sockets &&
    #                 rm -f tmp/pids/server.pid &&
    #                 bundle install &&
    #                 bundle exec puma -C config/puma.rb"
  web:
    build:
      # contextは読み込むDockerfileの場所を指定
      context: ./nginx
    ports:
      - "8088:80"
    volumes:
      - sock-data:/app/tmp
      - public-data:/app/public
    # backend起動後にwebを起動させる設定（依存関係）
    depends_on:
      - backend
    networks:
      - blog-app-network
      - default
  db:
    # :14.3つけないとエラー
    image: postgres:14.3
    env_file:
      - ./src/.env
    volumes:
    - db-data:/var/lib/postgresql/data
    networks:
      - blog-app-network
      - default
volumes:
  db-data:
  sock-data:
  public-data:
networks:
  blog-app-network:
    external: true