version: '3.9'

services:
  loadbalancer:
    build:
      # contextは読み込むDockerfileの場所を指定
      context: ./nginx
    ports:
      - "80:80"
    networks:
      - blog-app-network
      - default
networks:
  blog-app-network:
    external: true